import assert from 'node:assert/strict';import {mkdtemp,rm,mkdir} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve,sep} from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';
import {createApplication} from '../server/server.js';import {prepareAssets} from '../server/container.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const dir=await mkdtemp(join(tmpdir(),'drakon-inline-'));let app,browser;
const ru=v=>Array.isArray(v)?v.map(ru):v&&typeof v==='object'?Object.fromEntries(Object.entries(v).filter(([k])=>!['en','updated'].includes(k)).map(([k,x])=>[k,ru(x)])):v;
try{
 const assets=join(dir,'assets');await prepareAssets(assets);app=await createApplication({data:join(dir,'data'),assets,allowHTTP:true});await app.setPassword('inline-admin-password');await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:390,height:844}}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto(base);await p.locator('summary').click();await p.locator('#adminPassword').fill('inline-admin-password');await p.locator('#adminForm button').click();await p.waitForFunction(()=>S.role==='admin'&&!document.body.classList.contains('access-locked'));
 const get=()=>p.evaluate(()=>fetch('/api/content').then(r=>r.json())),initial=await get();
 await p.locator('[data-language="en"]').click();await p.waitForFunction(()=>S.role==='admin'&&EnglishUI.get()==='en'&&DAYS[0].title==='Here we go!');assert.equal(await p.locator('[data-dedit="0"]').innerText(),'Изменить день');assert.equal(await p.locator('html').getAttribute('lang'),'en');assert.equal(await p.locator('.nav [data-view="program"]').innerText(),'Programme');
 await p.locator('[data-dedit="0"]').click();assert.equal(await p.locator('#ddate').isDisabled(),true);await p.locator('#dtitle').fill('Inline English day');await p.locator('#dtext').fill('English paragraph only');await p.locator('#importantIntro').fill('English preparation instructions');await p.locator('#importantText0').fill('English WeChat advice');await p.locator('[data-act="srow-add"]').click();await p.locator('.di[data-f="time"]').last().fill('09:00');await p.locator('.di[data-f="what"]').last().fill('English-only event');await p.locator('#dform button[type="submit"]').click();await p.waitForFunction(()=>S.dayEdit===-1);await p.evaluate(()=>flushPending());let c=await get();assert.deepEqual(ru(c.program),ru(initial.program));assert.equal(c.program.days[0].en.title,'Inline English day');assert.equal(c.program.important.en.intro,'English preparation instructions');assert.equal(c.program.important.en.items[0][1],'English WeChat advice');assert.equal(c.program.days[0].en.schedule[0][1],'English-only event');
 await p.locator('[data-tedit="0"]').click();await p.locator('#ttitle').fill('Inline English task');await p.locator('#thint').fill('English task instructions');await p.locator('#tform button[type="submit"]').click();await p.evaluate(()=>flushPending());c=await get();assert.deepEqual(ru(c.tasks),ru(initial.tasks));assert.equal(c.tasks.tasks['2026-10-24'].en.title,'Inline English task');
 await p.locator('.nav [data-view="contacts"]').click();await p.locator('[data-act="site-edit"]').click();await p.locator('.ci[data-f="name"]').first().fill('English organiser');await p.locator('.ci[data-f="role"]').first().fill('English role');await p.locator('#contactNote').fill('English contact instructions');await p.evaluate(()=>flushPending());c=await get();assert.deepEqual(ru(c.site),ru(initial.site));assert.equal(c.site.contacts[0].en.name,'English organiser');assert.equal(c.site.en.contactNote,'English contact instructions');await p.locator('[data-act="site-off"]').click();
 await p.locator('[data-act="brand-edit"]').click();assert.equal(await p.locator('#loginTitle').inputValue(),'Leaders Tournament — 2026');await p.locator('#loginTitle').fill('English login title');await p.locator('#loginIntro').fill('English login instructions');await p.locator('#bfoot').fill('English footer');await p.evaluate(()=>flushPending());c=await get();assert.deepEqual(ru(c.site),ru(initial.site));assert.equal(c.site.login.en.title,'English login title');assert.equal(c.site.brand.en.footer,'English footer');await p.locator('[data-act="site-off"]').click();
 await p.evaluate(()=>{S.hEdit=true;S.edit=true;showView('people')});await p.locator('#cintro').fill('English draw instructions');await p.locator('.hi[data-f="name"]').first().fill('English house');await p.evaluate(()=>flushPending());c=await get();assert.deepEqual(ru(c.houses),ru(initial.houses));assert.equal(c.houses.ceremony.en.intro,'English draw instructions');assert.equal(c.houses.houses[0].en.name,'English house');await p.locator('[data-act="hedit-off"]').first().click();
 const id=initial.participants.people[0].id;await p.locator(`[data-pedit="${id}"]`).click();await p.locator('#pname').fill('English participant');await p.locator('#pbank').fill('English bank');await p.locator('#pform button[type="submit"]').click();await p.evaluate(()=>flushPending());c=await get();assert.equal(c.participants.people[0].name,initial.participants.people[0].name);assert.equal(c.participants.people[0].bank,initial.participants.people[0].bank);assert.equal(c.participants.people[0].name_en,'English participant');assert.equal(c.participants.people[0].bank_en,'English bank');assert.equal(c.invites[initial.participants.people[0].code],initial.invites[initial.participants.people[0].code]);
 await p.locator('[data-language="ru"]').click();await p.waitForFunction(()=>EnglishUI.get()==='ru');await p.evaluate(()=>{showView('program');selectDay(0)});assert.equal(await p.evaluate(()=>DAYS[0].title),initial.program.days[0].title);await p.locator('[data-dedit="0"]').click();await p.locator('#dtitle').fill('Русское изменение');await p.locator('#dform button[type="submit"]').click();await p.waitForFunction(()=>S.dayEdit===-1);await p.evaluate(()=>flushPending());c=await get();assert.equal(c.program.days[0].en.title,'Inline English day');assert.equal(c.program.days[0].title,'Русское изменение');
 await p.locator('[data-language="en"]').click();await p.waitForFunction(()=>EnglishUI.get()==='en');await p.reload();await p.waitForFunction(()=>S.role==='admin'&&EnglishUI.get()==='en');assert.equal(await p.evaluate(()=>DAYS[0].title),'Inline English day');
 const screenshots=fileURLToPath(new URL('./screenshots/',import.meta.url));await mkdir(screenshots,{recursive:true});await p.screenshot({path:join(screenshots,'inline-admin-en.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS: inline EN day/schedule/task/contact/login/footer/house/participant edits preserve RU; RU edits preserve EN; admin buttons RU; persisted language and invitation');
}finally{if(browser)await browser.close();if(app?.server.listening)await new Promise(r=>app.server.close(r));assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep+'drakon-inline-'));await rm(dir,{recursive:true,force:true});}
